// Types for the live Draft Room (manual draft logging + mock drafts).
// The draft is modeled as an append-only event log: all dashboards are
// derived from (config, pool, events) by pure functions in
// src/utils/draftEngine.ts, and undo is simply popping the last event.

import type { DraftType, RosterSlots } from './index';

export interface DraftRoomTeam {
  id: string;
  name: string;
  ownerName?: string;
}

// A pre-draft keeper: the player is reserved for the team and automatically
// consumes that team's pick in costRound (one round earlier than where he
// went last year, per the league's keeper rule).
export interface KeeperAssignment {
  teamId: string;
  playerId: string;
  costRound: number;
}

export interface DraftRoomConfig {
  // `${platform}:${leagueId}:${season}` — ties the saved session to a league.
  leagueKey: string;
  season: number;
  draftType: DraftType;
  // Order matters: this is the round-1 snake order / auction nomination order.
  teams: DraftRoomTeam[];
  myTeamId: string;
  rosterSlots: RosterSlots;
  // Per-team auction budget. Present but unused for snake drafts.
  budget: number;
  // Draftable spots per team (roster slots minus IR).
  rounds: number;
  mode: 'live' | 'mock';
  // Snake-only for now. Keeper players are held out of the pool and
  // auto-logged when the draft reaches their cost round.
  keepers?: KeeperAssignment[];
  // Mock-draft RNG seed. Set it to replay the same AI script after changing
  // strategy; left empty, each mock rolls fresh.
  simSeed?: number;
  // Mock auctions only: call bids out one at a time (you can price-enforce)
  // instead of submitting one sealed max bid.
  liveBidding?: boolean;
}

export type DraftEvent =
  | {
      kind: 'auction_sale';
      seq: number;
      ts: number;
      playerId: string;
      nominatedById: string;
      wonById: string;
      price: number;
      // Inflation-adjusted value shown when the sale was logged, so the pick
      // log's delta matches what the logger displayed. Older saved sessions
      // lack it; consumers fall back to the raw sheet value.
      expectedValue?: number;
    }
  | {
      kind: 'snake_pick';
      seq: number;
      ts: number;
      playerId: string;
      teamId: string;
      // Auto-logged keeper pick (not a live selection).
      isKeeper?: boolean;
    };

// Omit distributed over the DraftEvent union (a plain Omit collapses the
// union to its common fields). Used for logEvent inputs, where seq/ts are
// stamped by the hook.
type DistributiveOmit<T, K extends keyof T> = T extends unknown ? Omit<T, K> : never;
export type DraftEventInput = DistributiveOmit<DraftEvent, 'seq' | 'ts'>;

// One row of the bundled draft pool (src/data/draftPool.<season>.json),
// generated by scripts/buildDraftPool.ts from FantasyPros exports.
export interface PoolPlayer {
  id: string;
  name: string;
  team: string;
  pos: string;
  posRank: number;
  overallRank: number;
  tier: number;
  bye: number | null;
  // FantasyPros auction $ at the pool file's baseline league shape; null
  // below the salary sheet's cutoff (treated as $1 everywhere).
  baseValue: number | null;
  // Cross-source market data from npm run fetch:rankings (absent when the
  // source doesn't cover the player).
  espnAdp?: number;
  // Live ESPN auction market price, at ESPN's default league shape (10
  // teams, $200): a second opinion, not scaled to the user's league.
  espnValue?: number;
  // Sleeper half-PPR ADP.
  sleeperAdp?: number;
  // Sleeper ADP under other scoring formats, so non-half-PPR leagues see the
  // market that matches their rules (see sleeperAdpFor in utils/consensus.ts).
  sleeperAdpPpr?: number;
  sleeperAdpStd?: number;
  // Expert disagreement band around the consensus rank (FantasyPros
  // rank_min/rank_max/rank_std): wide band = the experts can't agree.
  rankMin?: number;
  rankMax?: number;
  rankStd?: number;
  // Sleeper season-long projected points by scoring format (half-PPR is the
  // unsuffixed default, matching sleeperAdp).
  projPts?: number;
  projPtsPpr?: number;
  projPtsStd?: number;
  // From Sleeper's players dump: id unlocks headshots
  // (sleepercdn.com/content/nfl/players/thumb/<id>.jpg).
  sleeperId?: string;
  // Questionable / Out / IR / PUP / Sus — absent when healthy.
  injuryStatus?: string;
  rookie?: boolean;
  // 1 = listed starter at the position on Sleeper's depth chart.
  depthChartOrder?: number;
}

export interface DraftPoolFile {
  season: number;
  generatedAt: string;
  baseline: { budget: number; teams: number; rounds: number };
  players: PoolPlayer[];
}
