// Fetches Sleeper's per-week projections and bundles each pool player's
// weekly SHAPE: his projected half-PPR points for weeks 1-17. The weekly
// roster model (utils/projectedRoster.ts) normalizes the shape into weights
// and applies them to the league-scoring-adjusted season total, so byes,
// suspensions, and late-season ramp-ups land in the right weeks while the
// scoring math stays where it already lives. Half-PPR alone is enough - a
// week's SHARE of the season barely moves across formats.
//
// Runs after build:draft-data in update:rankings (it joins against the
// freshly built pool), and standalone via `npm run build:weekly-shape`.
// Fetch failures are non-fatal, like the optional rankings sources: the
// previous bundled shape file stays in place and the Action stays green.

import { mkdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs';
import { currentDraftSeason } from './season';

const seasonArg = process.argv.find(a => a.startsWith('--season='));
const SEASON = seasonArg ? Number(seasonArg.split('=')[1]) : currentDraftSeason();

// Fantasy-relevant weeks; the model ignores week 18 (starters rest).
const WEEKS = 17;

interface SleeperWeeklyEntry {
  player_id: string | number;
  stats?: { pts_half_ppr?: number };
}

async function fetchWeek(week: number): Promise<Map<string, number>> {
  const url = `https://api.sleeper.app/projections/nfl/${SEASON}/${week}?season_type=regular`;
  const res = await fetch(url, { headers: { 'User-Agent': 'fantasy-football-analyzer' } });
  if (!res.ok) throw new Error(`week ${week}: HTTP ${res.status}`);
  const data = (await res.json()) as SleeperWeeklyEntry[];
  const out = new Map<string, number>();
  for (const entry of data) {
    const pts = entry.stats?.pts_half_ppr ?? 0;
    if (pts > 0) out.set(String(entry.player_id), Math.round(pts * 10) / 10);
  }
  return out;
}

async function main() {
  const poolPath = `src/data/draftPool.${SEASON}.json`;
  if (!existsSync(poolPath)) {
    console.error(`No pool at ${poolPath}; run build:draft-data first.`);
    process.exit(1);
  }
  const pool = JSON.parse(readFileSync(poolPath, 'utf8')) as {
    players: Array<{ id: string; sleeperId?: string }>;
  };

  let weekly: Map<string, number>[];
  try {
    weekly = [];
    for (let w = 1; w <= WEEKS; w++) {
      weekly.push(await fetchWeek(w));
    }
  } catch (err) {
    // Optional-source policy: losing a refresh keeps yesterday's shape
    // instead of reddening the daily Action.
    console.warn(`Weekly projections fetch failed, keeping the previous shape file: ${err}`);
    return;
  }

  // Bundle only pool players: keyed by the pool's stable id slug so the
  // runtime join is a plain map lookup.
  const players: Record<string, number[]> = {};
  let matched = 0;
  for (const p of pool.players) {
    if (!p.sleeperId) continue;
    const sid = String(p.sleeperId);
    const arr = weekly.map(m => m.get(sid) ?? 0);
    if (arr.every(v => v === 0)) continue;
    players[p.id] = arr;
    matched++;
  }

  // Off-season, Sleeper serves the weekly endpoints SUCCESSFULLY but empty.
  // A thin result must not clobber the last good file - the model degrades
  // to flat-with-bye either way, but stale shapes beat none at all.
  if (matched < 100 && existsSync(`src/data/weeklyShape.${SEASON}.json`)) {
    console.warn(
      `Weekly projections matched only ${matched} pool players; keeping the previous shape file.`,
    );
    return;
  }

  // Raw snapshot for debuggability, same shape as the other data/raw files.
  // After the guard, so an off-season no-op keeps the last useful snapshot.
  mkdirSync('data/raw', { recursive: true });
  writeFileSync(
    `data/raw/sleeper-weekly.${SEASON}.json`,
    JSON.stringify(
      {
        season: SEASON,
        fetchedAt: new Date().toISOString(),
        weeks: weekly.map((m, i) => ({ week: i + 1, players: Object.fromEntries(m) })),
      },
      null,
      1,
    ) + '\n',
  );

  // One player per line, metadata on its own lines: the update Action's
  // no-op guard ignores changed lines matching /generatedAt|fetchedAt/, so
  // a single-line file would hide EVERY data change behind its timestamp,
  // and a day's real movement should diff as the players who moved.
  const playerLines = Object.entries(players)
    .map(([id, arr]) => ` ${JSON.stringify(id)}: ${JSON.stringify(arr)}`)
    .join(',\n');
  const json =
    `{\n"season": ${SEASON},\n"generatedAt": ${JSON.stringify(new Date().toISOString())},\n` +
    `"weeks": ${WEEKS},\n"players": {\n${playerLines}\n}\n}\n`;
  writeFileSync(`src/data/weeklyShape.${SEASON}.json`, json);
  writeFileSync(
    'src/data/weeklyShape.ts',
    `// GENERATED by scripts/updateWeeklyShape.ts — do not edit by hand.
// The app imports the weekly projection shape through this module so a
// season rollover only changes generated files.
import shapeJson from './weeklyShape.${SEASON}.json';
import type { WeeklyShapeFile } from '@/types/weeklyShape';

export const WEEKLY_SHAPE = shapeJson as WeeklyShapeFile;
`,
  );
  console.log(`Weekly shape: ${matched}/${pool.players.length} pool players, ${WEEKS} weeks.`);
}

main().catch(err => {
  console.error(err);
  process.exit(1);
});
