// GENERATED by scripts/buildDraftPool.ts — do not edit by hand.
// The app imports the ADP history through this module so a season
// rollover only changes generated files.
import historyJson from './adpHistory.2026.json';
import type { AdpHistoryFile } from '@/types/adpHistory';

// Through unknown: TS infers a union of literal rank objects from the JSON
// (one shape per snapshot), which never unifies with Record<string, number>.
export const ADP_HISTORY = historyJson as unknown as AdpHistoryFile;
