// GENERATED by scripts/buildDraftPool.ts — do not edit by hand.
// The app imports the current draft pool through this module so a season
// rollover only changes generated files.
import poolJson from './draftPool.2026.json';
import type { DraftPoolFile } from '@/types/draft';

export const POOL = poolJson as DraftPoolFile;
