// GENERATED by scripts/buildDraftPool.ts — do not edit by hand.
// Pool metadata WITHOUT the player array. Import this (not draftPool.ts)
// from anything that loads on every route, so the full pool JSON stays out
// of the eager entry chunk. See buildDraftPool.ts for why.

export const POOL_SEASON = 2026;
export const POOL_GENERATED_AT = "2026-08-31T23:13:41.172Z";
export const POOL_BASELINE = {"budget":200,"teams":12,"rounds":14};

/** Top 5 of the consensus board, for the homepage hero. */
export const TOP_OF_BOARD = [
  {"id":"jahmyr-gibbs-rb","name":"Jahmyr Gibbs","pos":"RB","team":"DET","overallRank":1,"baseValue":58},
  {"id":"bijan-robinson-rb","name":"Bijan Robinson","pos":"RB","team":"ATL","overallRank":2,"baseValue":57},
  {"id":"jamarr-chase-wr","name":"Ja'Marr Chase","pos":"WR","team":"CIN","overallRank":3,"baseValue":66},
  {"id":"puka-nacua-wr","name":"Puka Nacua","pos":"WR","team":"LAR","overallRank":4,"baseValue":63},
  {"id":"jaxon-smithnjigba-wr","name":"Jaxon Smith-Njigba","pos":"WR","team":"SEA","overallRank":5,"baseValue":57},
] as const;
