// GENERATED by scripts/updateWeeklyShape.ts — do not edit by hand.
// The app imports the weekly projection shape through this module so a
// season rollover only changes generated files.
import shapeJson from './weeklyShape.2026.json';
import type { WeeklyShapeFile } from '@/types/weeklyShape';

export const WEEKLY_SHAPE = shapeJson as WeeklyShapeFile;
